include:
  - proxy.yaml

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile.python

    restart: always

    environment:
      DB_HOST: db
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}

    networks:
      backend:
        ipv4_address: 172.20.0.5

    depends_on:
      db:
        condition: service_healthy


  db:
    image: mysql:8

    restart: always

    env_file:
      - .env

    networks:
      backend:
        ipv4_address: 172.20.0.10

    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 20
